### ISSUE TITLE
Don't see the swift runtime binaries in 0.6.0

### ISSUE THREAD

**Issue by hggz** [colemancda/swift-armv7#12]
Thank you so much for your work setting up these toolchain scripts. I noticed in the 0.6.0 release the swift-armv7 artifact is pretty slim, and doesn't have any of the swift-front end binaries that previous releases had (like 0.5.1). Is this intended?

**Comment by xtremekforever** [comment]
For Swift 5.10 it turns out that using `cmake` to build Swift and the corelibs was easier than trying to patch the Swift build scripts. As such, it seems that building the entire 5.10 toolchain for armv7 is a big challenge and we haven't figured it out yet...not sure if we will be able to have time to do this either anytime soon.
